export const options = [
    {name: "remove_parenthesis", type:"bool"},
    {name: "rename_variables", type:"string"}
];
// export const options = [
//     {name: "fp.spacer.arith.solver", type:"unsigned int"},
//     {name: "fp.spacer.blast_term_ite_inflation", type:"unsigned int"},
//     {name: "fp.spacer.ctp", type:"bool"},
//     {name: "fp.spacer.dump_benchmarks", type:"bool"},
//     {name: "fp.spacer.dump_threshold", type:"double"},
//     {name: "fp.spacer.elim_aux", type:"bool"},
//     {name: "fp.spacer.eq_prop", type:"bool"},
//     {name: "fp.spacer.gpdr", type:"bool"},
//     {name: "fp.spacer.gpdr.bfs", type:"bool"},
//     {name: "fp.spacer.ground_pobs", type:"bool"},
//     {name: "fp.spacer.iuc", type:"unsigned int"},
//     {name: "fp.spacer.iuc.arith", type:"unsigned int"},
//     {name: "fp.spacer.iuc.debug_proof", type:"bool"},
//     {name: "fp.spacer.iuc.old_hyp_reducer", type:"bool"},
//     {name: "fp.spacer.iuc.print_farkas_stats", type:"bool"},
//     {name: "fp.spacer.iuc.split_farkas_literals", type:"bool"},
//     {name: "fp.spacer.keep_proxy", type:"bool"},
//     {name: "fp.spacer.logic", type:"symbol"},
//     {name: "fp.spacer.max_level", type:"unsigned int"},
//     {name: "fp.spacer.max_num_contexts", type:"unsigned int"},
//     {name: "fp.spacer.mbqi", type:"bool"},
//     {name: "fp.spacer.min_level", type:"unsigned int"},
//     {name: "fp.spacer.native_mbp", type:"bool"},
//     {name: "fp.spacer.order_children", type:"unsigned int"},
//     {name: "fp.spacer.p3.share_invariants", type:"bool"},
//     {name: "fp.spacer.p3.share_lemmas", type:"bool"},
//     {name: "fp.spacer.print_json", type:"symbol"},
//     {name: "fp.spacer.propagate", type:"bool"},
//     {name: "fp.spacer.push_pob", type:"bool"},
//     {name: "fp.spacer.push_pob_max_depth", type:"unsigned int"},
//     {name: "fp.spacer.q3", type:"bool"},
//     {name: "fp.spacer.q3.instantiate", type:"bool"},
//     {name: "fp.spacer.q3.qgen.normalize", type:"bool"},
//     {name: "fp.spacer.q3.use_qgen", type:"bool"},
//     {name: "fp.spacer.random_seed", type:"unsigned int"},
//     {name: "fp.spacer.reach_dnf", type:"bool"},
//     {name: "fp.spacer.reset_pob_queue", type:"bool"},
//     {name: "fp.spacer.restart_initial_threshold", type:"unsigned int"},
//     {name: "fp.spacer.restarts", type:"bool"},
//     {name: "fp.spacer.simplify_lemmas_post", type:"bool"},
//     {name: "fp.spacer.simplify_lemmas_pre", type:"bool"},
//     {name: "fp.spacer.simplify_pob", type:"bool"},
//     {name: "fp.spacer.trace_file", type:"symbol"},
//     {name: "fp.spacer.use_array_eq_generalizer", type:"bool"},
//     {name: "fp.spacer.use_bg_invs", type:"bool"},
//     {name: "fp.spacer.use_derivations", type:"bool"},
//     {name: "fp.spacer.use_euf_gen", type:"bool"},
//     {name: "fp.spacer.use_inc_clause", type:"bool"},
//     {name: "fp.spacer.use_inductive_generalizer", type:"bool"},
//     {name: "fp.spacer.use_lemma_as_cti", type:"bool"},
//     {name: "fp.spacer.use_lim_num_gen", type:"bool"},
//     {name: "fp.spacer.validate_lemmas", type:"bool"},
//     {name: "tr", type: "bool"},
//     {name: "fp.spacer.weak_abs", type:"bool"}
// ];

