export type depthItem = {index: string, depth: number}
export type resultItem = {index: string, result: string, SPACER_num_invariants: number}
export type memoryItem = {index: string, memory: number}
export type timeItem = {index: string, time: number}

export type timeDetailedItem = {
    index: string | undefined, 
    time: number,
    time_iuc_solver_get_iuc: number,
    time_iuc_solver_get_iuc_hyp_reduce1: number,
    time_iuc_solver_get_iuc_hyp_reduce2: number,
    time_iuc_solver_get_iuc_learn_core: number,
    time_pool_solver_proof: number,
    time_pool_solver_smt_total: number,
    time_pool_solver_smt_total_sat: number,
    time_pool_solver_smt_total_undef: number,
    time_spacer_ctp: number,
    time_spacer_init_rules: number,
    time_spacer_init_rules_pt_init: number,
    time_spacer_mbp: number,
    time_spacer_solve: number,
    time_spacer_solve_propagate: number,
    time_spacer_solve_pt_must_reachable: number,
    time_spacer_solve_reach: number,
    time_spacer_solve_reach_children: number,
    time_spacer_solve_reach_cluster: number,
    time_spacer_solve_reach_gen_bool_ind: number,
    time_spacer_solve_reach_gen_merge: number,
    time_spacer_solve_reach_gen_merge_cvx_cls: number,
    time_spacer_solve_reach_gen_wide: number,
    time_spacer_solve_reach_is_reach: number
}
export type dashboardConfig = {
    height: number,
    width: number,
    graphHeight: number,
    margin: {top: number; right:number; bottom:number; left:number;},
    font: {title: string; axis: string; label: string;},
    barNum: number
}
export type dataItem = {
    SPACER_cluster_out_of_gas: number,
    SPACER_expand_pob_undef: number,
    SPACER_inductive_level: number,
    SPACER_max_cluster_size: number,
    SPACER_max_cvx_reduced_dim: number,
    SPACER_max_query_lvl: number,
    SPACER_need_sage: number,
    SPACER_num_abstractions: number,
    SPACER_num_abstractions_failed: number,
    SPACER_num_abstractions_success: number,
    SPACER_num_active_lemmas: number,
    SPACER_num_cant_abstract: number,
    SPACER_num_ctp_blocked: number,
    SPACER_num_dim_reduction_success: number,
    SPACER_num_invariants: number,
    SPACER_num_is_invariant: number,
    SPACER_num_lemma_jumped: number,
    SPACER_num_lemmas: number,
    SPACER_num_mbp_failed: number,
    SPACER_num_merge_gen: number,
    SPACER_num_merge_gen_failed: number,
    SPACER_num_merge_gen_success: number,
    SPACER_num_no_over_approximate: number,
    SPACER_num_non_lin: number,
    SPACER_num_pobs: number,
    SPACER_num_propagations: number,
    SPACER_num_queries: number,
    SPACER_num_reach_queries: number,
    SPACER_num_refinements: number,
    SPACER_num_reuse_reach_facts: number,
    SPACER_num_sync_cvx_cls: number,
    SPACER_num_under_approximations: number,
    SPACER_pob_out_of_gas: number,
    SPACER_wide_attmpts: number,
    SPACER_wide_success: number,
    depth: number,
    index: string,
    max_memory: number,
    memory: number,
    result: string,
    time: number,
    time_iuc_solver_get_iuc: number,
    time_iuc_solver_get_iuc_hyp_reduce1: number,
    time_iuc_solver_get_iuc_hyp_reduce2: number,
    time_iuc_solver_get_iuc_learn_core: number,
    time_pool_solver_proof: number,
    time_pool_solver_smt_total: number,
    time_pool_solver_smt_total_sat: number,
    time_pool_solver_smt_total_undef: number,
    time_spacer_ctp: number,
    time_spacer_init_rules: number,
    time_spacer_init_rules_pt_init: number,
    time_spacer_mbp: number,
    time_spacer_solve: number,
    time_spacer_solve_propagate: number,
    time_spacer_solve_pt_must_reachable: number,
    time_spacer_solve_reach: number,
    time_spacer_solve_reach_children: number,
    time_spacer_solve_reach_cluster: number,
    time_spacer_solve_reach_gen_bool_ind: number,
    time_spacer_solve_reach_gen_merge: number,
    time_spacer_solve_reach_gen_merge_cvx_cls: number,
    time_spacer_solve_reach_gen_wide: number,
    time_spacer_solve_reach_is_reach: number
};
